//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.MiniShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.PhieuXuatNhapChiTiet = new HashSet<PhieuXuatNhapChiTiet>();
            this.XuatNhapTonNgay = new HashSet<XuatNhapTonNgay>();
            this.TonKho = new HashSet<TonKho>();
        }
    
        public int MaSanPham { get; set; }
        public int MaLoaiSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string DonViTinh { get; set; }
        public decimal SoLuongToiThieu { get; set; }
        public decimal SoLuongBaoDong { get; set; }
        public string KyHieu { get; set; }
        public int GiaNhap { get; set; }
        public int GiaXuatBanSi { get; set; }
        public int GiaXuatBanLe { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatNhapChiTiet> PhieuXuatNhapChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuatNhapTonNgay> XuatNhapTonNgay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TonKho> TonKho { get; set; }
    }
}
