//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.MiniShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatNhapTonNgay
    {
        public int ID { get; set; }
        public int MaKho { get; set; }
        public int MaSanPham { get; set; }
        public System.DateTime Ngay { get; set; }
        public decimal TonDauNgay { get; set; }
        public decimal NhapTrongNgay { get; set; }
        public decimal XuatTrongNgay { get; set; }
        public decimal TonCuoiNgay { get; set; }
        public decimal TonToiThieu { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
